# Configuration for ENeRF
configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/enerfi.yaml # network model configuration
    - configs/datasets/hangzhou/hangzhou.yaml # dataset usage configuration

val_dataloader_cfg:
    dataset_cfg:
        # prettier-ignore
        frame_sample: {{configs.dataloader_cfg.dataset_cfg.frame_sample}}
        use_vhulls: False
        vhulls_dir: surfs

model_cfg:
    sampler_cfg:
        n_planes: [32, 8]

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
