# Configuration for ENeRF
configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/enerfi.yaml # network model configuration
    - configs/datasets/hangzhou/hangzhou.yaml # dataset usage configuration
    - configs/specs/optimized.yaml

val_dataloader_cfg:
    dataset_cfg:
        # prettier-ignore
        frame_sample: {{configs.dataloader_cfg.dataset_cfg.frame_sample}}
        force_sparse_view: True
        view_sample: [0, null, 1]
        n_srcs_list: [3]
        use_vhulls: True
        cache_raw: False

# model_cfg:
#     sampler_cfg:
#         n_planes: [32, 8]

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
