dataloader_cfg: # we see the term "dataloader" as one word?
    dataset_cfg: &dataset_cfg
        data_root: data/raspi/20221102
        use_masks: True
        immask_crop: True
        imbound_crop: True
        masks_dir: mask
        ratio: 0.5 # scale images down during loading (thus affects rendering and testing)
        
        # world scale, unit: m
        near: 0.5
        far: 3.5
        bounds: [[-2.0, -2.0, -2.5], [2.0, 2.0, 2.5]]
        dist_opt_K: True # whether to resize the image so that after distortion, no black pixels will remain
        use_aligned_cameras: True

        frame_sample: [0, null, 1] # [begin, end, step]
        view_sample: [0, null, 1]

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
        frame_sample: [0, null, 1] # make rendering faster, controls which of the views and frames to load
        # focal_ratio: 0.5 # when generating completely novel views (volumetric_video_inference_dataset), use a smaller focal length to make the scene appear larger
    sampler_cfg:
        view_sample: [0, null, 1] # make rendering faster, if doing IBR, change the view_sample in sampler_cfg to control which view to render

model_cfg:
    sampler_cfg:
        bg_brightness: 0.0
    renderer_cfg:
        bg_brightness: 0.0
    supervisor_cfg:
        msk_loss_weight: 0.001

viewer_cfg:
    use_window_focal: True
    camera_cfg:
        world_up: [0, -1, 0] # this dataset uses a strange camera system, align it when using the viewer