_: &mlp_size
    xyzt_embedder_cfg:
        xyz_embedder_cfg:
            bounds: [[-3.0, -3.0, -3.0], [3.0, 3.0, 3.0]]

model_cfg:
    network_cfg:
        # <<: *mlp_size
        network_cfgs:
            '0': # coarse network config
                <<: *mlp_size
            '1': # coarse network config
                <<: *mlp_size
            '2': # fine network config
                <<: *mlp_size
