# Use normal as training prior and visualize normal

dataloader_cfg:
    dataset_cfg: &dataset_cfg
        use_normals: True

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg

model_cfg:
    network_cfg:
        train_store_norm: True
    supervisor_cfg:
        norm_loss_weight: 1.0e-6

runner_cfg:
    test_using_inference_mode: False
    visualizer_cfg:
        types: [RENDER, DEPTH, ALPHA, NORMAL]
