dataloader_cfg: # we see the term "dataloader" as one word?
    dataset_cfg: &dataset_cfg
        bounds: [[-5.0, -5.0, -5.0], [5.0, 5.0, 5.0]]
        masks_dir: mask
        vhull_thresh: 0.95
        count_thresh: 6 # common views

        use_aligned_cameras: True

        vhull_thresh_factor: 0.75
        vhull_count_factor: 1.0

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
    sampler_cfg:
        view_sample: [0, null, 20]

viewer_cfg:
    use_window_focal: True

model_cfg:
    sampler_cfg:
        points_aligned: True # already aligned surfs
