configs: configs/datasets/neural3dv/neural3dv.yaml # inherit from this config
dataloader_cfg:
    dataset_cfg: &dataset_cfg
        data_root: data/neural3dv/sear_steak

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
