configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/l3mhet.yaml # network model configuration
    - configs/datasets/raspi/raspi_static.yaml # dataset usage configuration
    - configs/specs/optcam.yaml
    - configs/specs/transient.yaml

# runner_cfg:
#     epochs: 100 # enough is enough
#     log_interval: 20
#     eval_ep: 10
#     save_ep: 10
#     save_latest_ep: 10

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
