dataloader_cfg: # we see the term "dataloader" as one word?
    dataset_cfg: &dataset_cfg
        data_root: data/hangzhou/20231014093437

        dist_opt_K: True
        # near: 0
        # far: 10
        bounds: [[-10.0, -10.0, -5.0], [10.0, 10.0, 5.0]]

        # masks_dir: bgmtv2
        vhull_thresh: 1.0
        count_thresh: 18 # common views
        vhull_padding: 0.02 # padding could just be larger, this should be mostly fine

        vhull_ctof_factor: 3.0 # larger size?
        vhull_thresh_factor: 1.0
        vhull_count_factor: 1.0
        coarse_discard_masks: False
        intersect_camera_bounds: False

        use_aligned_cameras: True # will center the bounding box
        force_sparse_view: True # the user will specify the view count
        view_sample: [0, 8, 1]
        frame_sample: [0, 45, 1] # only train for a thousand frames
        focal_ratio: 1.2

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
        near: 0.5 # more wiggle room during inference
        frame_sample: [0, 45, 15]
        interp_cfg:
            xyz_ratio: [1.0, 0.0, 0.25]
        temporal_range: [0, 1, 0, 1, 0]
    sampler_cfg:
        view_sample: [0, 8, 1]

runner_cfg:
    visualizer_cfg:
        video_fps: 15 # azure 15fps

viewer_cfg:
    use_window_focal: True
    camera_cfg:
        world_up: [-1, 0, 0]
